### ISSUE TITLE
Initial production rollout checklist

### ISSUE THREAD

**Issue by JonathonDunford** [SynDEX-Temporary-Name/BackEnd#5]
<a href="https://github.com/freeatnet"><img src="https://avatars0.githubusercontent.com/u/138289?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [freeatnet](https://github.com/freeatnet)**
_Tuesday Feb 13, 2018 at 19:15 GMT_
_Originally opened as https://github.com/forkdelta/backend-replacement/issues/24_

----

- [x] Add order recording (#8 -> #25)
- [x] Enable HTTPS
- [x] Deploy code on a separate instance (clean-slated staging instance for production)
- [ ] Add error logging with Sentry or rollbar (#15)
- [x] Update live interface config
- [x] Fix contract events backfill
- [x] Backfill some contract events
- [x] Verify stable (12-24 hrs) and fix bugs, if any (#28, #29, #30, and counting!)
- [x] Add ticker (#18)
- [ ] Add rate limiting
- [x] Announce to community

**Comment by JonathonDunford** [comment]
<a href="https://github.com/JonathonDunford"><img src="https://avatars1.githubusercontent.com/u/5281151?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [JonathonDunford](https://github.com/JonathonDunford)**
_Tuesday Feb 13, 2018 at 19:46 GMT_

----

We should probably do something to limit API requests so we don't get spammed to death immediately.

Maybe something that checks for requests from our official site, grants it unlimited access, and gives all others limited access for the time being.
